# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_historico.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Historico(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(40, 42, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welbank_dep_label = QtWidgets.QLabel(self.centralwidget)
        self.welbank_dep_label.setGeometry(QtCore.QRect(235, -15, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.welbank_dep_label.setFont(font)
        self.welbank_dep_label.setObjectName("welbank_dep_label")
        self.sentence = QtWidgets.QLabel(self.centralwidget)
        self.sentence.setGeometry(QtCore.QRect(175, 62, 291, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(21)
        font.setItalic(True)
        self.sentence.setFont(font)
        self.sentence.setObjectName("sentence")
        self.copyr_dep_label = QtWidgets.QLabel(self.centralwidget)
        self.copyr_dep_label.setGeometry(QtCore.QRect(10, 429, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(21)
        font.setItalic(False)
        self.copyr_dep_label.setFont(font)
        self.copyr_dep_label.setObjectName("copyr_dep_label")
        self.voltar_dep_button = QtWidgets.QPushButton(self.centralwidget)
        self.voltar_dep_button.setGeometry(QtCore.QRect(552, 422, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.voltar_dep_button.setFont(font)
        self.voltar_dep_button.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.voltar_dep_button.setObjectName("voltar_dep_button")
        self.line_dep = QtWidgets.QFrame(self.centralwidget)
        self.line_dep.setGeometry(QtCore.QRect(-23, 99, 711, 20))
        self.line_dep.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_dep.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_dep.setObjectName("line_dep")
        self.teladep_dep_label = QtWidgets.QLabel(self.centralwidget)
        self.teladep_dep_label.setGeometry(QtCore.QRect(262, 127, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.teladep_dep_label.setFont(font)
        self.teladep_dep_label.setObjectName("teladep_dep_label")
        self.line_dep_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_dep_2.setGeometry(QtCore.QRect(0, 402, 711, 20))
        self.line_dep_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_dep_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_dep_2.setObjectName("line_dep_2")
        self.hist_hist_listwidget = QtWidgets.QListWidget(self.centralwidget)
        self.hist_hist_listwidget.setGeometry(QtCore.QRect(123, 189, 390, 192))
        self.hist_hist_listwidget.setObjectName("hist_hist_listwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welbank_dep_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#f8f8f2;\">WEL</span><span style=\" color:#ffde00;\">BANK</span></p></body></html>"))
        self.sentence.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#f8f8f2;\">Modernidade e simplicidade é aqui.</span></p></body></html>"))
        self.copyr_dep_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#f8f8f2;\">&copy;welisoncopyright</span></p></body></html>"))
        self.voltar_dep_button.setText(_translate("MainWindow", "Voltar"))
        self.teladep_dep_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">HISTÓRICO</span></p><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Historico()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
